# Generated by Django 5.1.6 on 2025-02-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(max_length=200, verbose_name='должность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='third_name',
            field=models.CharField(max_length=200, verbose_name='отчество'),
        ),
    ]
