# Generated by Django 5.1.6 on 2025-02-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title_slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
