# Generated by Django 5.1.6 on 2025-02-15 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('place', models.CharField(max_length=200, verbose_name='место утсановки')),
                ('characteristic', models.TextField(blank=True, verbose_name='характеристика')),
                ('photo', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='users.category')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['slug'],
            },
        ),
    ]
