# Generated by Django 5.1.6 on 2025-02-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/% Y/% m/% d/', verbose_name='Фото'),
        ),
    ]
