# Generated by Django 5.1.6 on 2025-02-15 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_equipment_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='users.category', verbose_name='категория'),
        ),
    ]
