# Generated by Django 5.1.6 on 2025-02-20 18:08

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('users', '0011_equipment_tags_alter_journal_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='теги'),
        ),
    ]
