# Generated by Django 5.1.6 on 2025-03-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('users', '0012_alter_equipment_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='place',
            field=models.CharField(max_length=200, verbose_name='место установки'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['title', 'slug'], name='users_equip_title_93ac1b_idx'),
        ),
    ]
