# Generated by Django 5.1.6 on 2025-03-06 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_equipment_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='сотрудник'),
        ),
    ]
