# Generated by Django 5.1.6 on 2025-03-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_journal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(max_length=200, null=True, verbose_name='телефон'),
        ),
    ]
