# Generated by Django 5.1.6 on 2025-03-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='avatar/%Y/%m/%d/', verbose_name='Аватар'),
        ),
    ]
