# Generated by Django 5.1.6 on 2025-03-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shema_image', models.ImageField(blank=True, default=None, null=True, upload_to='shema/%Y/%m/%d/', verbose_name='Схемы')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'Схема',
                'verbose_name_plural': 'Схемы',
                'ordering': ['-time_create'],
            },
        ),
    ]
