# Generated by Django 5.1.6 on 2025-03-26 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_schema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schema',
            old_name='shema_image',
            new_name='schema_image',
        ),
    ]
