# Generated by Django 5.1.6 on 2025-03-26 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_shema_image_schema_schema_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='title',
            field=models.CharField(default=datetime.datetime(2025, 3, 26, 11, 54, 14, 904771, tzinfo=datetime.timezone.utc), max_length=200, unique=True, verbose_name='название'),
            preserve_default=False,
        ),
    ]
