# Generated by Django 5.1.6 on 2025-03-27 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_schema_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schema',
            new_name='SchemaEquipment',
        ),
    ]
